### ISSUE TITLE
可以配合微信发送客服消息来通知

### ISSUE THREAD

**Issue by JohnNiang** [NGLSL/2019-nCov#1]
具体参考：https://github.com/JohnNiang/wechat-starter-boot-spring

**Comment by NGLSL** [comment]
可以考虑一下，如果你比较有空的话，可以先修改，后优化。

**Comment by JohnNiang** [comment]
似乎需要服务号才行。

**Comment by NGLSL** [comment]
> 似乎需要服务号才行。

那就比较可惜了，我把最新的代码已经提交了。如果，你感兴趣的话可以看看，里面还有很多优化的地方。

**Comment by JohnNiang** [comment]
我自己根据你的 Job 实现了一个 timeline 的 monitor。

**Comment by JohnNiang** [comment]
：P

**Comment by NGLSL** [comment]
> 我自己根据你的 Job 实现了一个 timeline 的 monitor。

很棒，加强完善建议接入多通道

**Comment by JohnNiang** [comment]
最近可能因此而被封 QQ 号了。不敢乱来了。

**Comment by NGLSL** [comment]
> 最近可能因此而被封 QQ 号了。不敢乱来了。

可以用163
